# This file was generated by GoReleaser. DO NOT EDIT.
class Kut < Formula
  desc "Run commands more easily"
  homepage "https://github.com/bettercallshao/kut"
  version "0.5.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bettercallshao/kut/releases/download/v0.5.1/kut_0.5.1_darwin_amd64.zip"
    sha256 "87c37f4e316896d9fb71f88c69ab755aac45bbbed6fd4826e4d948c2439970b3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bettercallshao/kut/releases/download/v0.5.1/kut_0.5.1_linux_amd64.zip"
    sha256 "42ae1e6e09abebfc37e815a4a1535cdf9373e6f86b58467b95541b13c5818079"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/bettercallshao/kut/releases/download/v0.5.1/kut_0.5.1_linux_armv6.zip"
    sha256 "94c37978e75818e77acfdcb480485c8783cfb1d8f592f3de1c863c3c6b957ab0"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/bettercallshao/kut/releases/download/v0.5.1/kut_0.5.1_linux_arm64.zip"
    sha256 "688ba1e529c6854ecd23f5d22bea2f3a820633d8fd2c30575192c72085ae325e"
  end

  def install
    bin.install "kut"
    bin.install "kutd"
  end
end
