# This file was generated by GoReleaser. DO NOT EDIT.
class Kut < Formula
  desc "Run commands more easily"
  homepage "https://github.com/bettercallshao/kut"
  version "0.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bettercallshao/kut/releases/download/v0.5.0/kut_0.5.0_darwin_amd64.zip"
    sha256 "0747ab8399426be72beefba5cc86ebd144dcb6816ce5291ce371b118e8f8efb8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bettercallshao/kut/releases/download/v0.5.0/kut_0.5.0_linux_amd64.zip"
      sha256 "6c09dd6224fe79404c07512e0722d822af2bd7991680a623a0a13ee7b74286f5"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bettercallshao/kut/releases/download/v0.5.0/kut_0.5.0_linux_arm64.zip"
        sha256 "ed592490b93a85d73bd3f4b68e7669f11eab4be8f99fa88c271f39ee1cc1bfb7"
      else
        url "https://github.com/bettercallshao/kut/releases/download/v0.5.0/kut_0.5.0_linux_armv6.zip"
        sha256 "ff8227d801242ce95018be510e388068047a52a05a047b1166f68fa46447aabd"
      end
    end
  end

  def install
    bin.install "kut"
    bin.install "kutd"
  end
end
