# This file was generated by GoReleaser. DO NOT EDIT.
class Kut < Formula
  desc "Run commands easily"
  homepage "https://github.com/bettercallshao/kut"
  version "0.5.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bettercallshao/kut/releases/download/v0.5.2/kut_0.5.2_darwin_amd64.zip"
    sha256 "25f7ac7efdf4b22357c4bc032bb3c0e03e150149f1cd9e3d6a5b128400e3dbc2"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bettercallshao/kut/releases/download/v0.5.2/kut_0.5.2_linux_amd64.zip"
    sha256 "17b6aa78c7d184ac972ff8c7c310a2b36466c3688b9101056b6b3c88168ab648"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/bettercallshao/kut/releases/download/v0.5.2/kut_0.5.2_linux_armv6.zip"
    sha256 "87eaee88f2b985cc41581063ab042919d9bea55389043a14fc8aa8958b24ed17"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/bettercallshao/kut/releases/download/v0.5.2/kut_0.5.2_linux_arm64.zip"
    sha256 "293e3b66777b0a0c64b0dfb81a1f8fdffd56ae66ba0b2e1b8d5431bde7816cd7"
  end

  def install
    bin.install "kut"
    bin.install "kutd"
  end
end
