# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kwt < Formula
  desc "Run commands easily"
  homepage "https://github.com/bettercallshao/kwt"
  version "0.5.3"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/bettercallshao/kut/releases/download/v0.5.3/kut_0.5.3_darwin_amd64.zip"
    sha256 "50b2b59aac8ab68005c71bce70171665ba30b7739a143d981876333feb24714d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/bettercallshao/kut/releases/download/v0.5.3/kut_0.5.3_linux_amd64.zip"
    sha256 "31606093243377a556bd437972a3306ce7d072fb7c08929a7cc32cab3b71c6c2"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/bettercallshao/kut/releases/download/v0.5.3/kut_0.5.3_linux_armv6.zip"
    sha256 "d26f0806b5b8f1c9067ef14b75e148147f8657358d1c2fea200f56834c607504"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/bettercallshao/kut/releases/download/v0.5.3/kut_0.5.3_linux_arm64.zip"
    sha256 "d1bc223387a0007f91782ac63827e317d9531b95772ab642229f35a1fcba03c9"
  end

  def install
    bin.install "kut"
  end
end
